apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: tile38
  name: tile38-autoscaler
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: tile38-follower
  targetCPUUtilizationPercentage: 70
status:
  currentReplicas: 3
  desiredReplicas: 3